# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strapp < Formula
  desc ""
  homepage "https://github.com/mwei2509/strapp"
  version "1.11.0"

  on_macos do
    url "https://github.com/mwei2509/strapp/releases/download/v1.11.0/strapp_1.11.0_darwin_all.tar.gz"
    sha256 "2552859572aa4b4dff155d61e87f0cc948741b7234869b16000bd3200d8d3a0c"

    def install
      bin.install "strapp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mwei2509/strapp/releases/download/v1.11.0/strapp_1.11.0_linux_arm64.tar.gz"
      sha256 "6944aa0f7be0fab4ffd66efbf9132cfa3770d7ebf9356be5df478e488fe17c20"

      def install
        bin.install "strapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mwei2509/strapp/releases/download/v1.11.0/strapp_1.11.0_linux_amd64.tar.gz"
      sha256 "4209fcf791b2467bfc5ed4d231726780cc63af1fdeb8bba000b0424df4443f9b"

      def install
        bin.install "strapp"
      end
    end
  end
end
