# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strapp < Formula
  desc ""
  homepage "https://github.com/mwei2509/strapp"
  version "1.10.0"

  on_macos do
    url "https://github.com/mwei2509/strapp/releases/download/v1.10.0/strapp_1.10.0_darwin_all.tar.gz"
    sha256 "6682ef7619a031923201ceb031c9d09626d9a21e5c64815717582e3b84b7812c"

    def install
      bin.install "strapp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mwei2509/strapp/releases/download/v1.10.0/strapp_1.10.0_linux_arm64.tar.gz"
      sha256 "75b604ee0eb11b9446566007303e36b3d21373c3a316858b0b7ae7f73f88b401"

      def install
        bin.install "strapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mwei2509/strapp/releases/download/v1.10.0/strapp_1.10.0_linux_amd64.tar.gz"
      sha256 "ab1a4841df902541a3b293b1161bbfb04e5ccf587a10dbeaa2c66402788d9b7a"

      def install
        bin.install "strapp"
      end
    end
  end
end
